#!/bin/sh
#
#BATCH --verbose
#SBATCH --job-name=getFinalSplitPeaksAndSummits
#SBATCH --output=/scratch/las821/reports/slurm_finalSplitPeaksSummits_%j.out
#SBATCH --error=/scratch/las821/reports/slurm_finalSplitPeaksSummits_%j.err
#SBATCH --time=5:00:00
#SBATCH --nodes=1
#SBATCH --mem=20GB
#SBATCH --mail-type=ALL
#SBATCH --mail-user=las821@nyu.edu

module load r/intel/3.4.2
module load bedtools/intel/2.26.0

val=$SLURM_ARRAY_TASK_ID
params=`sed -n ${val}p files.txt`
args=(`echo $params | sed 's/\s/ /g'`)


peaksFinal="${args[0]}"
peakID="${peaksFinal%.*}"
splitOutput="${args[1]}"
splitID="${splitOutput%.*}"
summitsBed="${args[2]}"
summitID="${summitsBed%.*}"

###get peaks that were splitted file###
#this file has the macs peaks that were split and the number of split peaks per macs peak
peaksFinalSplitted="${peakID}_splitted.bed"

bedtools intersect -c -a $peaksFinal -b  $splitOutput > temp.bed
awk '(NR) && ($6 > 1 ) ' temp.bed > $peaksFinalSplitted

rm temp.bed

#get subpeaks.overlap.bed file
#this file has the macs peak infomation for each split summit generated by PeakSplitter
peaksFinalSorted="${peakID}_sorted.bed"

bedtools intersect -a $peaksFinal -b $splitOutput > temp.bed
sort -k1,1 -k2n  temp.bed > temp.sorted.bed
sort -k1,1 -k2n $peaksFinal > $peaksFinalSorted

#run the R script prepFilesForSplitPeaks.R to finish getting subpeaks.overlap.bed and to get the summits that match peaks_final.bed
summitsFinal="${summitID}_final.bed"
overlap="${splitID}.overlap.bed"

Rscript --no-save /scratch/cgsb/ercan/scripts/chip/slurm/prepFilesForSplitPeaks.R ${peaksFinalSorted} ${summitsBed} ${summitsFinal}

paste $splitOutput temp.sorted_1.bed > $overlap

rm temp.bed
rm temp.sorted.bed
rm temp.sorted_1.bed

#all files are now ready to input into getFinalSplitPeaksAndSummits.R
sampleID="${summitID%_*}"
splitPeaksFinal="${sampleID}_split_peaks_final.bed"
splitSummitsFinal="${sampleID}_split_summits_final.bed"

Rscript --no-save /scratch/cgsb/ercan/scripts/chip/slurm/getFinalSplitPeaksAndSummits.R ${peaksFinalSorted} ${summitsFinal} ${peaksFinalSplitted} ${overlap} ${splitPeaksFinal} ${splitSummitsFinal}

rm $peaksFinalSplitted
rm $peaksFinalSorted
rm $summitsFinal
rm $overlap

echo "Done"

exit 0;
